# Generated by Django 2.2.4 on 2019-08-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VulnerabilityID', models.TextField()),
                ('PkgName', models.TextField()),
                ('InstalledVersion', models.TextField()),
                ('FixedVersion', models.TextField()),
                ('Title', models.TextField()),
                ('Description', models.TextField()),
                ('Severity', models.TextField()),
                ('References', models.TextField()),
            ],
        ),
    ]
