# Generated by Django 2.2.4 on 2019-08-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VulnPages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VulnerabilityID', models.TextField(blank=True, null=True)),
                ('PkgName', models.TextField(blank=True, null=True)),
                ('InstalledVersion', models.TextField(blank=True, null=True)),
                ('FixedVersion', models.TextField(blank=True, null=True)),
                ('Title', models.TextField(blank=True, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Severity', models.TextField(blank=True, null=True)),
                ('References', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'VulnPages',
            },
        ),
    ]
